iRepWebApp/urls.py
from allauth.account.views import logout
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from iRep import views, api,httpError

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^accounts/', include('allauth.urls')),  # All auth
    url(r'^$', views.home, name='index'),
    # Localizations #
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # serve media
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
]

urlpatterns += [


    # sales force
    url(r'^salesForce/add/$', views.AddSalesForce, name='createSalesForce'),
    url(r'^(?P<slug>[-\w]+)/salesForce/list/$', views.ViewSalesForceDefault, name='viewSalesForceByUser'),
    url(r'^salesForce/edit/(?P<slug>[-\w]+)/', views.EditSalesForce, name='editSalesForce'),
    url(r'^salesForce/delete/(?P<slug>[-\w]+)/', views.DeleteSalesForce, name='DeleteSalesForce'),
    # Products
    url(r'^settings/(?P<slug>[-\w]+)/product/add/$', views.AddProduct, name='createProduct'),
    url(r'^settings/(?P<slug>[-\w]+)/product/list/$', views.ViewProduct, name='productList'),
    url(r'^settings/product/(?P<slug>[-\w]+)/$', views.ViewEditProduct, name='editProduct'),
    url(r'^settings/category/add/$', views.AddCategory, name='AddCategory'),
    url(r'^settings/delete_product/(?P<slug>[-\w]+)/$', views.DeleteProduct, name='DeleteProduct'),
    # Clients
    url(r'^client/(?P<slug>[-\w]+)/$', views.ViewClient, name='viewClient'),
    url(r'^client/edit/(?P<slug>[-\w]+)/$', views.EditClient, name='EditClient'),
    url(r'^client/(?P<slug>[-\w]+)/add/$', views.AddClient, name='AddClient'),
    url(r'^orders/(?P<slug>[-\w]+)/$', views.viewOrder, name='viewOrder'),
    url(r'^dashboard/(?P<slug>[-\w]+)/$', views.dashboard, name='dashboard'),
    url(r'^client_delete/(?P<slug>[-\w]+)/', views.DeleteClient, name='DeleteClient'),
    # schedual
    url(r'^scheduler/add/$', views.AddScheduler, name='AddScheduler'),
    url(r'^scheduler/edit/$', views.EditScheduler, name='EditScheduler'),
    url(r'^scheduler/delete/$', views.DeleteScheduler, name='DeleteScheduler'),

    # Froms
    url(r'^forms/(?P<slug>[-\w]+)/$', views.ViewForms, name='ViewForms'),
    url(r'^addForms/(?P<slug>[-\w]+)/add$', views.CreateForms, name='addForms'),
    url(r'^Forms/edit/(?P<slug>[-\w]+)/(?P<id>[-\w]+)', views.EditForms, name='editForms'),
    url(r'^forms/answer/$', views.ViewFormQuestionAnswer, name='ViewFormsQuestion'),
    url(r'^forms/export/(?P<id>.+)/$', views.exportForm, name='exportFormAnswer'),
    url(r'^forms/delete/(?P<id>.+)/$', views.DeleteForm, name='DeleteForm'),

    # Bill Board
    url(r'^billboard/(?P<slug>[-\w]+)/', views.billBoards, name='billBoards'),
    url(r'^newBillBoard/', views.newBillBoard, name='newBillBoards'),
    url(r'^editbillBoard/(?P<id>.+)/$', views.editBillBoard, name='editBillBoard'),

    # Export
    url(r'^salesForceExport/$', views.ExportSalesForce, name='salesForceExport'),
    url(r'^clientExport/$', views.ExportClients, name='clientExport'),
    url(r'^exportOrders/$', views.ExportOrders, name='orderExport'),
    url(r'^exportForms/$', views.ExportForms, name='formExport'),
    url(r'^exportProduct/$', views.ExportProduct, name='productExport'),
    url(r'^exportAuditRetails/$', views.ExportAuditRetails, name='auditRetailExport'),


    # Audit Retails
    url(r'^auditRetails/(?P<slug>[-\w]+)/$', views.auditRetails, name='auditRetails'),

    # Report
    url(r'^report/visit_tracking_by_sales_force/$', views.TrackingVisitReportBySalesForce,
        name='TrackingVisitReportBySalesForce'),

    url(r'^report/visit_tracking_by_client/$', views.ClientReport,
        name='ClientReport'),
]

urlpatterns += [
    # API
    url(r'^api/v1/login/$', api.SalesForceLogin, name='apiLogin'),
    url(r'^api/v1/salesfunnel/$', api.GetSalesFunnel, name='apiGetSalesFunnel'),
    url(r'^api/v1/catalog/(?P<slug>.+)/$', api.ProductCategory, name='apiProductCatalaog'),
    url(r'^api/v1/clients/(?P<slug>.+)/$', api.Clients, name='apiClients'),
    url(r'^api/v1/client/add/$', api.AddClient, name='apiAddClients'),
    url(r'^api/v1/client/orders/(?P<clientId>.+)/$', api.ClientsOrder, name='apiClientsOrder'),
    url(r'^api/v1/client/order/add/$', api.OrderCreate, name='apiOrderCreate'),

    url(r'^api/v1/schedual/sf/(?P<sales_force_id>.+)/$', api.ListSchedualerBySF, name='apiCorpSchedualBySF'),
    url(r'^api/v1/schedual/cl/(?P<client_id>.+)/$', api.ListSchedualerByCL, name='apiCorpSchedualByCL'),
    url(r'^api/v1/schedual/add/$', api.addSchedual, name='apiCorpSchedualAdd'),

    url(r'^api/v1/working/start/$', api.SalesForceTimeLineStart, name='apiSalesForceTimeLineStart'),
    url(r'^api/v1/working/end/$', api.SalesForceTimeLineEnd, name='apiSalesForceTimeLineEnd'),
    url(r'^api/v1/check/in/$', api.CheckIn, name='apiCheckIn'),
    url(r'^api/v1/check/out/$', api.CheckOut, name='apiCheckOut'),
    url(r'^api/v1/tracking/$', api.Track, name='apiTrack'),

    url(r'^api/v1/tags/(?P<slug>.+)/$', api.ListTags, name='apiListTags'),

    url(r'^api/v1/forms/(?P<slug>.+)/$', api.ListForms, name='apiListForms'),
    url(r'^api/v1/question_answer/$', api.QuestionAnswer, name='apiQuestionAnswer'),

    url(r'^api/v1/billboard/(?P<slug>.+)/$', api.ListBillboard, name='apiListBillboard'),

    # serve media
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),

]


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^trans/', include('rosetta.urls')),
    ]


handler404 = httpError.error_forbidden

iRep/forms.py
import datetime
from crispy_forms.bootstrap import PrependedText, AppendedText, Accordion, AccordionGroup, FieldWithButtons, \
    StrictButton
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Reset, Layout, Field, Fieldset, Div, HTML, Button
from django import forms
from django.forms import HiddenInput
from django.forms.formsets import BaseFormSet
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from iRep.api import Clients
from iRep.managers.Products import ProductManager
from iRep.managers.Tags import TagManager
from iRep.models import SalesForce, ProductGroup, Product, Corporate, UserProfile, Client, Forms, FormQuestions, \
    BillBoard


class SignupForm(forms.Form):
    name = forms.CharField(max_length=30, label=_('Name'),
                           widget=forms.TextInput(attrs={'placeholder': _(' Name')}), required=False)
    email = forms.CharField(max_length=64, label=_('Email'),
                            widget=forms.TextInput(attrs={'placeholder': _('E-mail address')}))
    address = forms.CharField(max_length=150, label=_('Address'),
                              widget=forms.TextInput(attrs={'placeholder': _('Address')}))
    mobile = forms.CharField(max_length=150, label=_('Phone'),
                             widget=forms.TextInput(attrs={'placeholder': _('Phone')}))
    corp_admin = forms.CharField(max_length=150, label=_('Corporate Admin'),
                                 widget=forms.TextInput(attrs={'placeholder': _('Corporate Admin')}))
    corp_admin_phone = forms.CharField(max_length=150, label=_('Corporate Admin Phone'),
                                       widget=forms.TextInput(attrs={'placeholder': _('Corporate Admin Phone')}))

    # def raise_duplicate_email_error(self):
    # # here I tried to override the method, but it is not called
    #     raise forms.ValidationError(
    #         _("An account already exists with this e-mail address."
    #           " Please sign in to that account."))

    def signup(self, request, user):
        user.first_name = self.cleaned_data['name']
        user.last_name = ''
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['email']
        user.save()
        # save corp
        corp = Corporate()
        corp.corporate_name = user.first_name
        corp.corporate_address_txt = self.cleaned_data['address']
        corp.mobile = self.cleaned_data['mobile']
        corp.email = self.cleaned_data['email']
        corp.admin_name = self.cleaned_data['corp_admin']
        corp.admin_mobile = self.cleaned_data['corp_admin_phone']
        corp.created_by = user
        corp.slug = slugify('%s %s' % (user.get_full_name(), user.id), allow_unicode=True)
        corp.save()
        # save profile
        profile = UserProfile()
        profile.auth_user = user
        profile.corporate = corp
        profile.user_type = 1
        profile.save()


class BaseReportForm(forms.Form):
    report_date = [(0, _('Today')), (1, _('Yesterday')), (7, _('This week')), (14, _('Last Week')),
                   (30, _('This month')), (60, _('Last month')), (365, _('This year')), (730, _('This year'))]
    date_from = forms.DateField()
    date_to = forms.DateField()
    static_range = forms.ChoiceField(choices=report_date)


class SalesForceForm(forms.ModelForm):
    company_id = forms.CharField()

    def __init__(self, *args, **kwargs):
        # Get data from kwargs
        user_instance = kwargs.pop('user_instance', None)
        corp_instance = kwargs.pop('corp_instance', None)
        action = kwargs.pop('action', None)
        super(SalesForceForm, self).__init__(*args, **kwargs)
        # init data
        if corp_instance:
            self.fields['company_id'].initial = corp_instance.slug
            self.fields['report_to'].queryset = SalesForce.objects.filter(corp_id=corp_instance)
        # self.fields['user_pin'].initial = user_instance.id
        # control Required
        self.fields['avatar'].required = False
        self.fields['name'].required = True
        self.fields['password_pin'].required = True
        self.fields['user_pin'].required = True
        self.fields['notes'].required = False
        self.fields['company_id'].required = True
        self.fields['position'].required = True
        self.fields['report_to'].required = False

        # control readOnly
        self.fields['company_id'].widget.attrs['readonly'] = True
        self.fields['user_pin'].widget.attrs['readonly'] = False

        # input name
        self.fields['avatar'].label = _('Upload Image')
        self.fields['name'].label = _('Name')
        self.fields['phone'].label = _('Phone')
        self.fields['email'].label = _('E-mail')
        self.fields['profile_language'].label = _('Profile Language')
        self.fields['user_pin'].label = _('App UserID')
        self.fields['password_pin'].label = _('App Password')
        self.fields['notes'].label = _('Notes')
        self.fields['is_active'].label = _('active sales force')
        self.fields['company_id'].label = _('Company ID')
        self.fields['position'].label = _('Position')
        self.fields['report_to'].label = _('Reporting to')
        self.fields['serial_number'].label = _('Serial number')

        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)
        self.helper.form_id = 'sales-force-form-id'
        self.helper.form_method = 'post'
        self.helper.form_action = action
        self.helper.layout = Layout(
            Field('avatar', css_class=''),
            Div(css_class='clearfix'),
            Div(css_class='divider-lg'),
            Div(
                Div(
                    Div(
                        Field('name', placeholder=_('Enter sales force name')),
                        Field('phone', placeholder=_('Enter phone number')),
                        Field('email', placeholder=_('Enter e-mail address')),
                        css_class='col-md-6'
                    ),
                    Div(
                        Field('position', empty_label=_('Enter e-mail address')),
                        Field('profile_language', empty_label=_('Select profile language')),
                        Field('is_active'),
                        Field('report_to', empty_label=_('Reporting to')),
                        css_class='col-md-6'
                    ),
                    Div(css_class='clearfix'),

                    Div(Fieldset(_('Activation Data'),
                                 PrependedText('company_id', '<i class="fa fa-building" aria-hidden="true"></i>',
                                               css_class='col-md-6', placeholder=_('Company ID')),
                                 PrependedText('user_pin', '<i class="fa fa-user" aria-hidden="true"></i>',
                                               css_class='col-md-6', placeholder=_('App UserID')),
                                 PrependedText('password_pin', '<i class="fa fa-key" aria-hidden="true"></i>',
                                               css_class='col-md-6',
                                               placeholder=_('App Password')),

                                 PrependedText('serial_number', '<i class="fa fa-key" aria-hidden="true"></i>',
                                               css_class='col-md-6',
                                               placeholder=_('Device Serial')),
                                 ),
                        css_class='col-md-6')
                    ,

                    Div(
                        Fieldset(_('Other'), Field('notes', placeholder=_('Write some notes about sales force'))),
                        css_class='col-md-6')
                    ,
                    Div(
                        Reset(_('Cancel'), _('Cancel'), css_class='btn btn-default  btn-lg min-btn'),
                        Submit(_('Save'), _('Save'), css_class='btn btn-primary  btn-lg min-btn'),
                        css_class='text-center'
                    ),
                    css_class='panel-body'
                ),
                css_class='panel panel-default'
            ))

    # override save form
    def save(self, user, commit=True):
        m = super(SalesForceForm, self).save(commit=False)
        m.corp_id = Corporate.objects.get(slug=self.cleaned_data['company_id'])
        m.created_by = user
        m.slug = slugify('%s %s' % (m.name, user.id), allow_unicode=True)
        m.save()
        return m

    class Meta:
        model = SalesForce
        exclude = ['last_activity', 'created_date', 'created_by', 'corp_id', 'slug']


class SalesForceReportForm(BaseReportForm):
    sales_force = forms.CharField()

    def __init__(self, *args, **kwargs):
        sales_force_id = kwargs.pop('sales_force', None)
        super(SalesForceReportForm, self).__init__(*args, **kwargs)
        # initial
        self.fields['date_from'].initial = datetime.datetime.today()
        self.fields['date_to'].initial = datetime.datetime.today()
        self.fields['sales_force'].widget = forms.HiddenInput()
        if sales_force_id:
            self.fields['sales_force'].initial = str(sales_force_id)

        # override label
        self.fields['date_from'].label = ''
        self.fields['date_to'].label = ''
        # self.fields['static_range'].label = ''

        # It builds a default layout with all its fields
        self.helper = FormHelper(self)
        self.helper.form_id = 'sales-force-form-report-id'
        self.helper.form_method = 'post'
        self.helper.form_action = None
        self.helper.layout = Layout(
            Div(
                AppendedText('date_from',
                             '<span class="glyphicon glyphicon-calendar"></span>',
                             placeholder=_('Start date'))

templates/sales_force/details.html
{% extends 'base/base.html' %}
{% load i18n staticfiles crispy_forms_tags %}
{% block extra_head %}
    <link rel='stylesheet' href="{% static 'full_calendar/fullcalendar.min.css' %}"/>
    {#    <link rel='stylesheet' href="{% static 'full_calendar/fullcalendar.print.css' %}"/>#}
    <link rel="stylesheet" href="{% static 'css/development.css' %}">
{% endblock %}
{% block content %}
    <div class="body bs-example">
        <h1 class="sub-titile"><i class="glyphicon glyphicon-user"></i>
            {% if not new %}{{ form.name.value }}{% else %}
                {% trans 'New representative' %}{% endif %} {{ form.id.value }}</h1>
        <div>
            <ul class="nav nav-tabs sales-tabs" role="tablist">
                <li role="presentation" class="active">
                    <a href="#info" aria-controls="home" role="tab" {% if not new %}data-toggle="tab"{% endif %}>
                        {% trans 'Sales force Info' %}
                    </a>
                </li>
                <li role="presentation">
                    <a href="#report" aria-controls="profile" role="tab" {% if not new %}data-toggle="tab"{% endif %}>
                        {% trans 'Report' %}
                    </a>
                </li>
                <li role="presentation">
                    <a href="#schedual" aria-controls="messages" role="tab"
                       {% if not new %}data-toggle="tab"{% endif %}>
                        {% trans 'Schedule' %}
                    </a>
                </li>

            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane fade in active" id="info">
                    {% crispy form %}
                </div>
                <div role="tabpanel" class="tab-pane fade in active" id="report">
                    <div class="divider-md"></div>
                    <div class="top-controlbar">
                        {% if reportForm %}
                            {% crispy reportForm %}
                        {% endif %}
                        <div class="clearfix"></div>
                    </div>

                    {% include 'sales_force/reports.html' %}


                </div>
                <div role="tabpanel" class="tab-pane fade in active" id="schedual">
                    <div class="divider-md"></div>
                    <div id='calendar'></div>
                </div>

            </div>
        </div>

    </div>
    {% include 'schedual/schedual_visit_modal.html' %}
    {% include 'schedual/schedual_visit_modal_edit.html' %}
{% endblock %}
{% block extra_js_src %}
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'app_js/highcharts.js' %}"></script>
    {#    <script src="{% static 'app_js/exporting.js' %}"></script>#}
    <script src="{% static 'full_calendar/fullcalendar.min.js' %}"></script>
    <script src="{% static 'app_js/scheduler.js' %}"></script>
    <script src="{% static 'app_js/common.js' %}"></script>
    <script src="{% static 'app_js/sales_force.js' %}"></script>
{% endblock %}
{% block extra_javascript %}
    <script>
        $(function () {
            $('#id_date_from').datetimepicker({
                format: 'YYYY-MM-DD'
            });
            $('#id_date_to').datetimepicker({
                format: 'YYYY-MM-DD'
            });
            
            $('#time').datetimepicker({
                format: 'hh:ii'
            });
        });


        $(document).ready(function () {
            var data = {{ clients|safe }};


            $('#client').select2({
                placeholder: '--------',
                data: data
            });

            $('#client_edit').select2({
                placeholder: '--------',
                data: data
            })
            // page is now ready, initialize the calendar...

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                defaultView: 'month',
                eventLimit: true,
                editable: true,
                dayClick: function (date, jsEvent, view) {
                    if (moment().format('YYYY-MM-DD') === date.format('YYYY-MM-DD') || date.isAfter(moment())) {
                        // This allows today and future date
                        $('#myModal').modal('show');
                        $("#date").val(date.format('YYYY-MM-DD'));
                        $('#dataTxt').text(date.format('YYYY-MM-DD'));
                        $('#salesRepName').val('{{ form.name.value }}');
                        $('#salesRepName').attr('readonly', 'readonly');
                    }

                },
                events: [{% for row in schedular %}
                    {
                        "id":'{{ forloop.counter0 }}',
                        "start": '{{ row.schedual_date |date:"o-m-d"}}',
                        "end": '{{ row.schedual_date |date:"o-m-d"}}',
                        "title": '{{ row.branch.name }}',
                        'backgroundColor': '#378006',
                        "time": '{{ row.schedual_time }}',
                        "custom_data": '{{ row.getObjectAsJson|safe }}'

                    },
                {% endfor %}],
                eventClick: function (event) {

                    var dataAll = (JSON.parse(event.custom_data));
                    var data = dataAll[0].fields;
                    console.log(dataAll);

                    $('#myModaledit').modal('show');
                    $("#myModaledit #date").val(data.schedual_date);
                    $("#myModaledit #dataTxt").text(data.schedual_date);
                    $('#myModaledit #id').val(dataAll[0].pk);

                    $('#myModaledit #time').val(data.schedual_time);
                    $('#myModaledit #salesRepName').val('{{ form.name.value }}');
                    $('#myModaledit #salesRepName').attr('readonly', 'readonly');
                    $('#myModaledit #client_edit').val(data.branch);
                    $('#myModaledit #notes').val(data.notes);
                    $('#myModaledit #edit').attr('onclick','editSchedular('+event.id+')');
                    $('#myModaledit #delete').attr('onclick','deleteSchedular('+event.id+')');
                }


            });

        });
    </script>
{% endblock %}

templates/sales_force/efforts.html
{% load i18n %}
<div class="col-md-12"><h1 class="sub-titile">{% trans 'Effort' %}</h1></div>
<div class="row" id="effort">
    <div class="col-sm-12 col-md-3">
        <div class="thumbnail report-blk">

            <div class="caption">
                <small>{% trans 'Days active' %}</small>
                <h3 id="countDay">0</h3>
                <p>{% trans 'Total number of days with activities' %}</p>

            </div>
        </div>
    </div>


    <div class="col-sm-12 col-md-3">
        <div class="thumbnail report-blk">

            <div class="caption">
                <small>{% trans 'Working time' %}</small>
                <h3 id="hr">0h:0m</h3>
                <p> {% trans 'Total working time' %}
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-md-3">
        <div class="thumbnail report-blk">

            <div class="caption">
                <small>{% trans 'Mileage (km)' %}</small>
                <h3 id="km">0</h3>
                <p>{% trans 'Total Mileage' %}
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-md-3">
        <div class="thumbnail report-blk">

            <div class="caption">
                <small>{% trans 'Visited places' %}</small>
                <h3 id="totalVisits">0</h3>
                <p>{% trans 'Total visited places' %}
            </div>
        </div>
    </div>

</div>

templates/sales_force/list.html
{% extends 'base/base.html' %}
{% load i18n staticfiles %}
{% block extra_head %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css">
{% endblock %}
{% block content %}
    <div class="body bs-example">
    <h1 class="sub-titile">
        <i class="glyphicon glyphicon-user"></i> {% trans 'Sales force' %}
    </h1>
        <a href="{% url 'createSalesForce' %}" class="btn btn-primary  " >
            <i class="glyphicon glyphicon-plus-sign coloring1"></i> {% trans 'Sales force' %}
        </a>

        <a href="{% url 'salesForceExport' %}" class="btn btn-info  " >
            <i class="glyphicons glyphicons-file-export"></i> {% trans 'Export' %}
        </a>
    <div class="outer">
    <div class="col-md-12">
        <div id="collapse4" class="body">
            <table id="dataTable" class="table table-bordered table-condensed table-hover table-striped">
                <thead>
                <tr>
                    <th>--</th>
                    <th>{% trans 'Name' %}</th>
                    <th>{% trans 'Last Activity' %}</th>
                    <th>{% trans 'Active' %}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for row in salesForce %}
                    <tr>
                        <td>
                            {% if row.avatar  %}
                                 <img src="{{ row.avatar.url }}">
                            {% endif %}
                        </td>
                        <td><a href="{% url 'editSalesForce' row.slug %}">{{ row.name }}</a></td>
                        <td>{{ row.last_activity }}</td>
                        <td>{{ row.is_active }}</td>
                        <td><a href="{% url 'DeleteSalesForce' row.slug %}" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i></a></td>
                    </tr>
                {% endfor %}

                </tbody>

            </table>

        </div>

    </div>

    <div>


    </div>
{% endblock %}
{% block extra_js_src %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.26.6/js/jquery.tablesorter.min.js"></script>
{% endblock %}
{% block extra_javascript %}
    <script>
        $(function () {
            Metis.MetisTable();
            Metis.metisSortable();
        });
    </script>
{% endblock %}

templates/sales_force/reports.html
{% load i18n %}
<div class="row">
    {% include 'sales_force/topStatistics.html' %}
</div>
{#{% include 'sales_force/chart.html' %}#}
{% include 'sales_force/visits_track.html' %}
{% include 'sales_force/efforts.html' %}

templates/sales_force/topStatistics.html
{% load i18n %}
<div class="col-sm-12 col-md-4">
    <div class="thumbnail report-blk">

        <div class="caption">
            <small>{% trans 'Time at place' %}</small>
            <h3 id="totalTimePlace">{% trans '0h:0m' %}</h3>
            <p>{% trans 'Total time spent at place' %}</p>

        </div>
    </div>
</div>

<div class="col-sm-12 col-md-4">
    <div class="thumbnail report-blk">

        <div class="caption">
            <small>{% trans 'Place visits' %}</small>
            <h3 id="totalVisitGroupByBranch">0</h3>
            <p>{% trans 'Total time spent at place' %}</p>

        </div>
    </div>
</div>


<div class="col-sm-12 col-md-4">
    <div class="thumbnail report-blk">

        <div class="caption">
            <small>{% trans 'Activities' %}</small>
            <h3 id="totalOrder">0</h3>
            <p>{% trans 'Total Orders' %}</p>

        </div>
    </div>
</div>

templates/sales_force/visit_track_rows.html
{% load i18n %}

<table class="table tracking-table" >
    <thead>
    <tr>
        <th>{% trans 'Client' %}</th>
        <th>{% trans 'status' %}</th>
        <th>{% trans 'CheckIn Date\Time' %}</th>
        <th>{% trans 'CheckOut Date\Time' %}</th>
        <th>{% trans 'Meeting Duration' %}</th>
        <th>{% trans 'Forms' %}</th>


    </tr>
    </thead>
    <tbody>
    {% for row in tracking %}
        <tr>
            <td>{{ row.branch.name }} </td>
            {% if row.get_sec < 0 %}
                <td><span class="label label-info">{% trans 'Early' %}</span></td>
            {% elif row.get_sec == 0 %}
                <td><span class="label label-success">{% trans 'On time' %}</span></td>
            {% else %}
                <td><span class="label label-danger">{% trans 'Delay' %}  {{ row.getDelay }}</span></td>
            {% endif %}

            <td><span class="label label-primary">{{ row.check_in_date }}</span>{{ row.check_in_time }}</td>

            <td><span class="label label-danger">{{ row.check_out_date }}</span>{{ row.check_out_time }}</td>
            <td>{{ row.getTimeDiff }}</td>
            <td><a href="{% url 'exportFormAnswer' row.visit.id %}" download="iREP-File01"><i class="glyphicon glyphicon-save-file" download=""></i>Download</a></td>

        </tr>
    {% empty %}
        <tr>
            <td>{% trans 'No data found' %}</td>
        </tr>

    {% endfor %}
    </tbody>

</table>